before:
  hooks:
    - go mod tidy

builds:
  - binary: nbacli
    goos:
      - darwin
      - linux
      - windows
    env:
      - CGO_ENABLED=0

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: nbacli
    homepage: https://github.com/dylantientcheu/nbacli
    tap:
      owner: dylantientcheu
      name: homebrew-dylantientcheu
    commit_author:
      name: Dylan Tientcheu
      email: dylantientcheu@gmail.com

checksum:
  name_template: 'checksums.txt'