before:
  hooks:
    - go mod tidy

builds:
  - binary: nbacli
    goos:
      - darwin
      - linux
      - windows
    env:
      - CGO_ENABLED=0

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

release:
  prerelease: auto

universal_binaries:
  - replace: true

# brew distro
brews:
  -
    name: nbacli
    homepage: https://github.com/dylantientcheu/nbacli
    tap:
      owner: dylantientcheu
      name: homebrew-dylantientcheu
    commit_author:
      name: Dylan Tientcheu
      email: dylantientcheu@gmail.com

# chocolatey distro
chocolateys:
  -
    name: nbacli
    title: NBA CLI
    authors: Dylan TIENTCHEU
    project_url: https://github.com/dylantientcheu/nbacli
    url_template: "https://github.com/dylantientcheu/nbacli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    icon_url: 'https://raw.githubusercontent.com/dylantientcheu/nbacli/master/screenshots/logo.png'
    copyright: 2023 Dylan Tientcheu
    license_url: https://github.com/dylantientcheu/nbacli/blob/main/LICENSE
    require_license_acceptance: false
    project_source_url: https://github.com/dylantientcheu/nbacli
    docs_url: https://github.com/dylantientcheu/nbacli/blob/main/README.md
    bug_tracker_url: https://github.com/dylantientcheu/nbacli/issues
    tags: "nbacli nba terminal standings stats scores"
    summary: The NBA in your terminal.
    description: |
      {{ .ProjectName }} installer package.
      The NBA in your terminal

    release_notes: "https://github.com/dylantientcheu/nbacli/releases/tag/v{{ .Version }}"
    dependencies:
      - id: lipgloss
        version: 0.6.0
      - id: bubbles
        version: 0.14.0
      - id: cobra
        version: 1.6.1
    api_key: '{{ .Env.CHOCOLATEY_API_KEY }}'
    source_repo: "https://push.chocolatey.org/"
    skip_publish: false
    goamd64: v1

checksum:
  name_template: 'checksums.txt'