builds:
  - binary: nbacli
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: nbacli
    homepage: https://github.com/dylantientcheu/nbacli
    tap:
      owner: dylantientcheu
      name: homebrew-dylantientcheu
    commit_author:
      name: dylantientcheu
      email: dylantientcheu@gmail.com

checksum:
  name_template: 'checksums.txt'